template:
  root: ./template
  serviceClass: jp.co.cyberagent.aeromock.template.freemarker.FreemarkerTemplateService

data:
  root: ../data

static:
  root: ../static

ajax:
  root: ../json/ajax

tag:
  root: ./tag

function:
  root: ./function

